DROP TABLE IF EXISTS sharks;

CREATE TABLE sharks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sharkname TEXT NOT NULL,
    followers INTEGER,
    rating INTEGER
);